apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: peoplefinder-ingress
  namespace: peoplefinder-demo
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: peoplefinder-ingress-peoplefinder-demo-green
    external-dns.alpha.kubernetes.io/aws-weight: "0"
spec:
  tls:
    - hosts:
      - demo.peoplefinder.service.gov.uk
      secretName: peoplefinder-certificate
  rules:
    - host: demo.peoplefinder.service.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: peoplefinder-service
              servicePort: 3000
